# Generated by Django 4.1.3 on 2023-01-11 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_datetime_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='user_liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Post Likes'),
        ),
    ]
