# Generated by Django 4.1.3 on 2023-01-11 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='user_liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Post Likes'),
        ),
    ]
